spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_HOST}
    password: ${DATABASE_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PW}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expire-time: ${JWT_ACCESS_EXPIRE_TIME}
  refresh-token-expire-time: ${JWT_REFRESH_EXPIRE_TIME}

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack:
      auto: false
    region:
      static: ${BUCKET_REGION}
    credentials:
      accessKey: ${BUCKET_ACCESSKEY}
      secretKey: ${BUCKET_SECRETKEY}

external:
  facial-api-url: ${FACIAL_API_URL}
  speech-api-url: ${SPEECH_API_URL}
